version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "echoes-mysql:/var/lib/mysql"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
networks:
  backend:
    driver: bridge
volumes:
  echoes-mysql:
    driver: local